# Make sure to activate the venv environment before using the pre-commit hooks
repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        entry: black  # Make sure black is available in the environment (venv)
        language_version: python3

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint  # Make sure pylint is available in the environment (venv)
        language: python
        types: [python]
        args: [--errors-only]
      - id: unittest
        name: Run unittest
        entry: python -m unittest discover  # Make sure unittest is available in the environment (venv)
        language: system
        pass_filenames: false
        always_run: true