version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # Ensure GPU is reserved
    runtime: nvidia  # Use NVIDIA runtime explicitly
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Make sure all GPUs are visible to the container
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility  # Capabilities required for GPU usage
