services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Make sure all GPUs are visible to the container
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility  # Capabilities required for GPU usage
      - MODEL_DIR=${MODEL_DIR}
      - HF_TOKEN=${HF_TOKEN}
      - HF_MODEL_ID=${HF_MODEL_ID}
    volumes:
      - ${MODEL_DIR}:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia  # Use NVIDIA runtime explicitly